# define BSR_FLAVOR_BLUESPACE "bluespace"
# define BSR_FLAVOR_CHIMERA "chimera"
# define BSR_FLAVOR_CHAOTIC "chaotic"
# define BSR_FLAVOR_DEMONIC "demonic"
# define BSR_FLAVOR_OCCULT "occult"
# define BSR_FLAVOR_VAMPIRE "vampire"

# define BSR_ALL_FLAVORS_LIST list(BSR_FLAVOR_BLUESPACE, BSR_FLAVOR_CHIMERA, BSR_FLAVOR_OCCULT, BSR_FLAVOR_DEMONIC, BSR_FLAVOR_VAMPIRE)
