GLOBAL_LIST_EMPTY(trigger_landmarks)
GLOBAL_LIST_EMPTY(ship_projectile_landmarks)
GLOBAL_LIST_EMPTY(target_projectile_landmarks)

GLOBAL_LIST_EMPTY(overmap_ships)

GLOBAL_LIST_EMPTY(simple_mob_list) //List of all alive simplemobs