#define HOME_SYSTEM_RYCLIES   "Ryclies I"
#define HOME_SYSTEM_READE   "Reade III"
#define HOME_SYSTEM_PROCYON   "Procyon"

#define FACTION_ORMA     "Outer Rim Miners Alliance"

#define CULTURE_HUMAN_ORMA	"ORMA Spacer"
#define CULTURE_HUMAN_NT	"NanoTrasen Spacer"

#define HOME_SYSTEM_TERSTEN    "Tersten"
#define HOME_SYSTEM_LORRIMAN   "Lorriman"
#define HOME_SYSTEM_CINU       "Cinu"
#define HOME_SYSTEM_YUKLID     "Yuklid V"
#define HOME_SYSTEM_LORDANIA   "Lordania"
#define HOME_SYSTEM_KINGSTON   "Kingston"

/datum/map/glloydstation
	available_cultural_info = list(
		TAG_HOMEWORLD = list(
			HOME_SYSTEM_MARS,
			HOME_SYSTEM_LUNA,
			HOME_SYSTEM_VENUS,
			HOME_SYSTEM_CERES,
			HOME_SYSTEM_PLUTO,
			HOME_SYSTEM_TAU_CETI,
			HOME_SYSTEM_HELIOS,
			HOME_SYSTEM_TERSTEN,
			HOME_SYSTEM_LORRIMAN,
			HOME_SYSTEM_CINU,
			HOME_SYSTEM_YUKLID,
			HOME_SYSTEM_LORDANIA,
			HOME_SYSTEM_KINGSTON,
			HOME_SYSTEM_GAIA,
			HOME_SYSTEM_RYCLIES,
			HOME_SYSTEM_READE,
			HOME_SYSTEM_PROCYON,
			HOME_SYSTEM_OTHER
		),
		TAG_FACTION = list(
			FACTION_NANOTRASEN,
			FACTION_XYNERGY,
			FACTION_HEPHAESTUS,
			FACTION_SOL_CENTRAL ,
			FACTION_PCRC,
			FACTION_ORMA,
			FACTION_OTHER
		),
		TAG_CULTURE = list(
			CULTURE_HUMAN,
			CULTURE_HUMAN_MARTIAN,
			CULTURE_HUMAN_MARSTUN,
			CULTURE_HUMAN_LUNAPOOR,
			CULTURE_HUMAN_LUNARICH,
			CULTURE_HUMAN_VENUSIAN,
			CULTURE_HUMAN_VENUSLOW,
			CULTURE_HUMAN_BELTER,
			CULTURE_HUMAN_PLUTO,
			CULTURE_HUMAN_CETIU,
			CULTURE_HUMAN_SPACER,
			CULTURE_HUMAN_SPAFRO,
			CULTURE_HUMAN_ORMA,
			CULTURE_HUMAN_NT,
			CULTURE_HUMAN_OTHER,
			CULTURE_OTHER
		),
		TAG_RELIGION = list(
			RELIGION_OTHER,
			RELIGION_JUDAISM,
			RELIGION_HINDUISM,
			RELIGION_BUDDHISM,
			RELIGION_ISLAM,
			RELIGION_CHRISTIANITY,
			RELIGION_AGNOSTICISM,
			RELIGION_DEISM,
			RELIGION_ATHEISM,
			RELIGION_THELEMA,
			RELIGION_SPIRITUALISM
		)
	)

	default_cultural_info = list(
		TAG_HOMEWORLD = HOME_SYSTEM_MARS,
		TAG_FACTION =   FACTION_SOL_CENTRAL,
		TAG_CULTURE =   CULTURE_HUMAN_MARTIAN,
		TAG_RELIGION =  RELIGION_AGNOSTICISM
	)

/datum/language/human/euro
	warning = "Automatically given if spawning on the station."
