# Docs - https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/syntax-for-githubs-form-schema
name: Bug Report
description: File a bug report
labels: ["Bug", "Needs Triage"]

body:
  - type: markdown
    attributes:
      value: |
        Make sure to [search for an existing issue report](https://github.com/UristMcStation/UristMcStation/issues) before making a new one.

        Your issue will be tagged by a developer with reproduction status and a priority once it has been reviewed and verified.
  - type: textarea
    id: desc
    attributes:
      label: Description of issue
      placeholder: The macguffin doesn't do anything when used.
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Difference between expected and actual behaviour
      placeholder: The macguffin should kill the big bad when I use it.
  - type: textarea
    id: repro-steps
    attributes:
      label: Steps to reproduce
      description: Please provide a complete step-by-step method of reproducing the bug, including steps you may think are obvious. Also please make sure you have followed and verified these steps to reproduce the bug yourself. Being verbose is better than being vague. If reproduction is unreliable, i.e., it only happens sometimes or only happened once, mention that in the reproduction steps.
      placeholder: |
        1.
        2.
        3.
        ...
    validations:
      required: true
  - type: textarea
    id: paths
    attributes:
      label: Specific information for locating
      description: e.g. an object name, specific message outputs, object paths or file names if known, specific maps and/or coordinates, etc
      placeholder: |
        Item name: The MacGuffin
        Big bad name: Very Evil Mob
        Item path: `/obj/item/macguffin`
  - type: textarea
    id: version
    attributes:
      label: Client version, server revision, & game ID
      description: This is found with the `Show server revision` verb in the OOC tab in game, or typing `show-server-revision` into the chat.
      placeholder: |
        Client Version: 514
        Server Revision: 34bf3ff6a39a09848d5552e0486c0f0fedb58fc9 - dev - 2022-08-06
        Game ID: cji-cImG
        Current map: SEV Torch
    validations:
      required: true
  - type: checkboxes
    id: issue-bingo
    attributes:
      label: Issue bingo
      description: Check all that apply. Try to tick off all of these before you submit the report.
      options:
        - label: Issue could be reproduced at least once
        - label: Issue could be reproduced by different players
        - label: Issue could be reproduced in multiple rounds
        - label: Issue happened in a recent (less than 7 days ago) round
        - label: "[Couldn't find an existing issue about this](https://github.com/UristMcStation/UristMcStation/issues)"
