/datum/map/glloydstation
// Unit test exemptions
	apc_test_exempt_areas = list(
		/area/AIsattele = NO_SCRUBBER|NO_VENT|NO_APC,
		/area/construction = NO_SCRUBBER|NO_VENT,
		/area/constructionsite = NO_SCRUBBER|NO_VENT|NO_APC,
		/area/constructionsite/ai = NO_SCRUBBER|NO_VENT,
		/area/constructionsite/atmospherics = NO_SCRUBBER,
		/area/constructionsite/teleporter = NO_SCRUBBER,
		/area/derelict/ship = NO_SCRUBBER|NO_VENT,
		/area/engineering/atmos/storage = NO_SCRUBBER|NO_VENT,
		/area/holodeck = NO_SCRUBBER|NO_VENT|NO_APC,
		/area/maintenance = NO_SCRUBBER|NO_VENT,
		/area/maintenance/arrivals = NO_SCRUBBER,
		/area/maintenance/atmos_control = 0,
		/area/maintenance/auxsolarport = NO_SCRUBBER,
		/area/maintenance/auxsolarstarboard = NO_SCRUBBER,
		/area/maintenance/dormitory = NO_SCRUBBER,
		/area/maintenance/engi_shuttle = NO_SCRUBBER,
		/area/maintenance/evahallway = NO_SCRUBBER,
		/area/maintenance/medbay = NO_SCRUBBER,
		/area/maintenance/incinerator = NO_SCRUBBER,
		/area/maintenance/foresolar = NO_SCRUBBER,
		/area/maintenance/portsolar = NO_SCRUBBER,
		/area/maintenance/research_port = 0,
		/area/maintenance/research_starboard = NO_SCRUBBER,
		/area/maintenance/starboardsolar = NO_SCRUBBER,
		/area/medical/genetics = NO_APC,
		/area/mine/explored = NO_SCRUBBER|NO_VENT,
		/area/mine/unexplored = NO_SCRUBBER|NO_VENT|NO_APC,
		/area/outpost/abandoned = NO_SCRUBBER|NO_VENT|NO_APC,
		/area/outpost/mining_main/maintenance = NO_SCRUBBER|NO_VENT,
		/area/rescue_base = NO_SCRUBBER|NO_VENT|NO_APC,
		/area/rnd/test_area = NO_SCRUBBER|NO_VENT,
		/area/rnd/server = 0,
		/area/shuttle = NO_SCRUBBER|NO_VENT|NO_APC,
		/area/skipjack_station = NO_SCRUBBER|NO_VENT|NO_APC,
		/area/solar = NO_SCRUBBER|NO_VENT|NO_APC,
		/area/space = NO_SCRUBBER|NO_VENT|NO_APC,
		/area/storage/emergency = NO_SCRUBBER|NO_VENT,
		/area/storage/emergency2 = NO_SCRUBBER|NO_VENT,
		/area/supply = NO_SCRUBBER|NO_VENT|NO_APC,
		/area/syndicate_station = NO_SCRUBBER|NO_VENT|NO_APC,
		/area/maintenance/exterior = NO_SCRUBBER|NO_VENT|NO_APC
	)

	area_coherency_test_exempt_areas = list(
			/area/space,
			/area/mine/explored,
			/area/mine/unexplored,
			/area/centcom/control,
			/area/engineering/atmos,
			/area/constructionsite,
			/area/constructionsite/maintenance,
			/area/solar/constructionsite,
			/area/maintenance/exterior,
			/area/awaymission/maze,
			/area/maintenance/incinerator)

	area_usage_test_exempted_areas = list(
		/area/awaymission,
		/area/scom/mission,
		/area/scom/mission/lighting,
		/area/shuttle/scom/s1/mission,
		/area/shuttle/scom/s1/mission0,
		/area/shuttle/scom/s1/mission1,
		/area/shuttle/scom/s1/mission2,
		/area/shuttle/scom/s1/mission3,
		/area/shuttle/scom/s1/mission4,
		/area/shuttle/scom/s1/mission5,
		/area/shuttle/scom/s1/mission6,
		/area/shuttle/scom/s1/mission7,
		/area/shuttle/scom/s1/mission11,
		/area/shuttle/scom/s1/mission12,
		/area/shuttle/scom/s1/mission13,
		/area/shuttle/scom/s1/mission14,
		/area/shuttle/scom/s1/mission15,
		/area/shuttle/scom/s2/mission,
		/area/shuttle/scom/s2/mission0,
		/area/shuttle/scom/s2/mission1,
		/area/shuttle/scom/s2/mission2,
		/area/shuttle/scom/s2/mission3,
		/area/shuttle/scom/s2/mission4,
		/area/shuttle/scom/s2/mission5,
		/area/shuttle/scom/s2/mission6,
		/area/shuttle/scom/s2/mission7,
		/area/shuttle/scom/s2/mission11,
		/area/shuttle/scom/s2/mission12,
		/area/shuttle/scom/s2/mission13,
		/area/shuttle/scom/s2/mission14,
		/area/shuttle/scom/s2/mission15,
		/area/shuttle/event1/l1,
		/area/shuttle/event1/l2,
		/area/shuttle/event1/l3,
		/area/shuttle/event2/l1,
		/area/shuttle/event2/l2,
		/area/shuttle/event2/l3,
		/area/shuttle/assault/a1/station,
		/area/shuttle/assault/a2/station,
		/area/shuttle/infestation/i1/station,
		/area/shuttle/infestation/i1/ship,
		/area/shuttle/infestation/i2/station,
		/area/shuttle/infestation/i2/ship,
		/area/shuttle/train/stop,
		/area/shuttle/train/go,
		/area/shuttle/naval1/event1,
		/area/shuttle/naval1/event2,
		/area/shuttle/naval1/event3
	)