// Uncomment defines as needed to enable various loggers.

// # define RAYTRACE_DEBUG_LOGGING 0
// # define ADD_ACTION_DEBUG_LOGGING 0
// # define OBSTACLEHUNT_DEBUG_LOGGING 0
// # define VALIDATE_ACTION_DEBUG_LOGGING 0
# define ACTION_RUNTIME_DEBUG_LOGGING 0
# define ACTIONTRACKER_DEBUG_LOGGING 0
# define PLANNING_DEBUG_LOGGING 0
# define MOTIVES_DEBUG_LOGGING 0