
# ifdef GOAI_LIBRARY_FEATURES
GOAI_ACTIONSET_FROM_FILE_BOILERPLATE(/obj/item/gun, GOAI_SMARTOBJECT_PATH("gun.json"))
GOAI_HAS_UTILITY_ACTIONS_BOILERPLATE_INVENTORY_SIMPLE(/obj/item/gun)
# endif


# ifdef GOAI_SS13_SUPPORT
GOAI_ACTIONSET_FROM_FILE_BOILERPLATE(/obj/item/gun, GOAI_SMARTOBJECT_PATH("gun.json"))
GOAI_HAS_UTILITY_ACTIONS_BOILERPLATE_INVENTORY_SIMPLE(/obj/item/gun)
# endif
