name: Cancel
on:
  push:
    branches:
      - baymerge-testing

# NB: We can discover workflow IDs for this job at https://api.github.com/repos/ORG/REPO/actions/workflows
jobs:
  cancel:
    name: 'Cancel Redundant Builds'
    permissions:
      actions: write # required to cancel other actions
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
      - uses: styfle/cancel-workflow-action@01ce38bf961b4e243a6342cbade0dbc8ba3f0432
        with:
          workflow_id: 3545321
          access_token: ${{ github.token }}
