name: 'Close stale issues and PRs'

permissions:
  contents: read

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
    inputs:
      dry-run:
        description: "Dry Run"
        type: boolean
        default: false
        required: true

jobs:
  stale:
    permissions:
      issues: write # required to close stale issues
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v9
        with:
          stale-issue-message: 'This issue has not been updated in 30 days, and will close in 5 days from now if no updates are made. Please address any outsanding queries from maintainers. If you have already done this and you are auto-staled anyway, ask a maintainer for an update.'
          close-issue-message: 'This issue was closed because it has been stalled for 5 days with no activity.'
          any-of-issue-labels: 'Awaiting Response'
          exempt-issue-labels: 'Stale-b-gone'
          stale-pr-message: 'This pull request has not been updated in 30 days, and will close in 7 days from now if no updates are made. Please address any outstanding review items and ensure your pull request is finished. If you have already done this and you are auto-staled anyway, ask a maintainer for an update.'
          close-pr-message: 'This pull request was closed because it has been stalled for 7 days with no activity.'
          exempt-draft-pr: true
          exempt-pr-labels: 'CALL THE SHUTTLE,fuuuuuuuuuuuuck,Stale-b-gone'
          exempt-pr-assignees: 'Glloyd'
          days-before-stale: 30
          days-before-close: 5
          days-before-pr-close: 7
          operations-per-run: 50
          debug-only: ${{ inputs.dry-run }}
