name: "Pull Request Labeler"

permissions:
  contents: read

on:
  pull_request_target:
    branches:
      - baymerge-testing
      - master

jobs:
  triage:
    permissions:
      contents: read # may be required due to overwrite/add ambiguity
      pull-requests: write # required to apply labels to PRs
    runs-on: ubuntu-latest
    steps:
    - uses: actions/labeler@v5
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
        sync-labels: true
