/datum/map/wyrm

	apc_test_exempt_areas = list(
		/area/space = NO_SCRUBBER|NO_VENT|NO_APC,
		/area/rnd/xenobiology/xenoflora_storage = NO_SCRUBBER|NO_VENT,
		/area/engineering/extsubmaint = NO_SCRUBBER,
		/area/maintenance/construction = NO_APC,
		/area/engineering/teg = NO_SCRUBBER|NO_VENT,
		/area/engineering/externalmaint = NO_SCRUBBER,
		/area/engineering/atmos = NO_SCRUBBER,
		/area/maintenance/primary/fp = NO_SCRUBBER|NO_VENT,
		/area/pod/start = NO_SCRUBBER|NO_VENT,
		/area/maintenance/primary/engp = NO_SCRUBBER|NO_VENT|NO_APC,
		/area/engineering/atmosmon = NO_SCRUBBER|NO_VENT,
		/area/maintenance/primary/fs = NO_SCRUBBER|NO_VENT,
		/area/maintenance/primary/sec = NO_SCRUBBER|NO_VENT,
		/area/maintenance/primary/engs = NO_SCRUBBER|NO_VENT,
		/area/maintenance/primary/cargo = NO_SCRUBBER|NO_VENT,
		/area/holodeck = NO_SCRUBBER|NO_VENT|NO_APC,
		/area/rescue/start = NO_SCRUBBER,
		/area/exoplanet          = NO_SCRUBBER|NO_VENT|NO_APC,
		/area/exoplanet/desert   = NO_SCRUBBER|NO_VENT|NO_APC,
		/area/exoplanet/grass    = NO_SCRUBBER|NO_VENT|NO_APC,
		/area/exoplanet/snow     = NO_SCRUBBER|NO_VENT|NO_APC,
	)

	area_usage_test_exempted_areas = list(
		/area/AIsattele,
		/area/djstation,
		/area/outpost,
		/area/outpost/abandoned,
		/area/centcom/holding,
		/area/centcom/specops,
		/area/centcom/holding,
		/area/chapel,
		/area/security/prison,
		/area/shuttle/escape/centcom,
		/area/shuttle/specops/centcom,
		/area/shuttle/syndicate_elite/mothership,
		/area/map_template/skipjack_station/start,
		/area/syndicate_elite_squad,
		/area/map_template/wizard_station,
		/area/beach,
		/area/template_noop,
		/area/overmap,
		/area/infestation,
		/area/boarding_ship
	)

	area_usage_test_exempted_root_areas = list(
		/area/casino,
		/area/constructionsite,
		/area/derelict,
		/area/lost_supply_base,
		/area/magshield,
		/area/mine,
		/area/ship,
		/area/smugglers,
		/area/slavers_base,
		/area/yacht,
		/area/bluespaceriver,
		/area/mobius_rift,
		/area/icarus,
		/area/errant_pisces,
		/area/lar_maria,
		/area/map_template,
		/area/exoplanet,
		/area/lanius,
		/area/planet/jungle,
		/area/scom,
		/area/shuttle/naval1,
		/area/shuttle/scom,
		/area/shuttle/train,
		/area/shuttle/event1,
		/area/shuttle/event2,
		/area/shuttle/assault,
		/area/shuttle/infestation,
		/area/awaymission,
		/area/outpost,
		/area/away
	)
